<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-05-12T03:27:42Z" name="Default suite" finished-at="2021-05-12T03:27:49Z" duration-ms="6694">
    <groups>
    </groups>
    <test started-at="2021-05-12T03:27:42Z" name="Default test" finished-at="2021-05-12T03:27:49Z" duration-ms="6694">
      <class name="selenium.Topic_01_Check_Environment">
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:selenium.Topic_01_Check_Environment@ba2f4ec]" started-at="2021-05-12T03:27:43Z" name="beforeClass" finished-at="2021-05-12T03:27:49Z" duration-ms="6072" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method signature="TC_01_ValidateCurrentUrl()[pri:0, instance:selenium.Topic_01_Check_Environment@ba2f4ec]" started-at="2021-05-12T03:27:49Z" name="TC_01_ValidateCurrentUrl" finished-at="2021-05-12T03:27:49Z" duration-ms="10" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_01_ValidateCurrentUrl -->
        <test-method signature="TC_02_ValidatePageTitle()[pri:0, instance:selenium.Topic_01_Check_Environment@ba2f4ec]" started-at="2021-05-12T03:27:49Z" name="TC_02_ValidatePageTitle" finished-at="2021-05-12T03:27:49Z" duration-ms="8" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_02_ValidatePageTitle -->
        <test-method signature="TC_03_LoginFormDisplayed()[pri:0, instance:selenium.Topic_01_Check_Environment@ba2f4ec]" started-at="2021-05-12T03:27:49Z" name="TC_03_LoginFormDisplayed" finished-at="2021-05-12T03:27:49Z" duration-ms="49" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at selenium.Topic_01_Check_Environment.TC_03_LoginFormDisplayed(Topic_01_Check_Environment.java:49)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_03_LoginFormDisplayed -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:selenium.Topic_01_Check_Environment@ba2f4ec]" started-at="2021-05-12T03:27:49Z" name="afterClass" finished-at="2021-05-12T03:27:49Z" duration-ms="534" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- selenium.Topic_01_Check_Environment -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
